version: '3.1'
services:
  mysql:
    env_file: ./.env
    image: mysql:5.7
    container_name: mysql
    environment:
      "MYSQL_DATABASE": "wizeauth"
      "MYSQL_ROOT_PASSWORD": "69F2AF93541E1EA838F40EE3744EFF60FEDF13F8C0CC07F12643C41589CBA6B1"
    ports:
      - "3307:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"